export enum ROW_STATUS {
  AG_VALIDACAO = 'AG VALIDAÇÃO',
  EM_ANALISE = 'EM ANÁLISE',
  ANALISE_CONCLUIDA = 'ANÁLISE CONCLUÍDA',
  NAO_LOCALIZADO = 'NÃO LOCALIZADO',
  SEM_ACESSO_BANCARIO = 'SEM ACESSO BANCÁRIO',
  VALIDADO = 'VALIDADO',
}